

CREATE TABLE IF NOT EXISTS Books(
    Id INT NOT NULL PRIMARY KEY,
    Title VARCHAR(255) NOT NULL,
    Description VARCHAR(1000));

CREATE TABLE IF NOT EXISTS Users(
    Id INT NOT NULL PRIMARY KEY,
    FirstName VARCHAR(255) NOT NULL,
    LastName VARCHAR(255) NOT NULL,
    Role VARCHAR(50) NOT NULL );

CREATE TABLE IF NOT EXISTS UsersBooks(
    UserId INT NOT NULL,
    BookId INT NOT NULL,
    EndDate DATE NOT NULL,
    PRIMARY KEY(UserId, BookId),
    FOREIGN KEY (UserId) REFERENCES Users (Id),
    FOREIGN KEY (BookId) REFERENCES Books (Id));